#include "EE3420.INC"
    ORG $1000
NUM DC.B #$FF
PRIME DC.B #1
    ORG $2000
MAIN: ;THIS WILL BE THE FIRST LINE OF CODE EXECUTED
    LDY NUM ;INDEX Y = VALUE FROM MEMORY LOCATION NUM
    DEY
LOOP1:
    CLRA
    CLRB
    LDAB NUM
    TFR Y,X
    IDIV
    CPD #0
    BEQ UNSETPRIME
    DEY
    CPY #1
    BEQ DONE
    BRA LOOP1    
UNSETPRIME:
    LDAA #0
    STAA PRIME
DONE:
    RTS ;END OF "MAIN" FUNCTION