#include "EE3420.INC"
    ORG $1000
SUM DC.W 0 ;DEFINES ONE WORD INITIALIZED TO 0
AVG DC.W 0 ;DEFINES ONE WORD INITIALIZED TO 0
MAX DC.B 0 ;DEFINES ONE WORD INITIALIZED TO 0
MIN DC.B 0 ;DEFINES ONE WORD INITIALIZED TO 10
ARRAY DC.B FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF ;DEFINES and array of 18 BYTE Sized Integers UNINITIALIZED
    ORG $2000
MAIN: ;THIS WILL BE THE FIRST LINE OF CODE EXECUTED
    CLRA
    CLRB
    LDX #17 ;INDEX X = 17
    LDY ARRAY ;INDEX Y = VALUE FROM MEMORY LOCATION VAR2
LOOP1:
    ADDD 0,Y ;ADD 3 TO THE CONTENTS OF ACCUMULATOR A
    INCY
    DBNE X,LOOP1 ;DECREMENT X AND BRANCH TO LOOP1 IF RESULT
        ;IS NOT EQUAL TO ZERO
    STD SUM ;PLACE HEXADECIMAL VALUE ABCD IN MEMORY
        ;AT LOCATION VAR3
    LDX #18
    IDIV
    STX AVG
    CLRA
    CLRB
    LDX #16 ;INDEX X = 17
    LDY ARRAY ;INDEX Y = VALUE FROM MEMORY LOCATION VAR2
    LDA 0,ARRAY
LOOP2:
    MINA 0,Y ;ADD 3 TO THE CONTENTS OF ACCUMULATOR A
    INCY
    DBNE X,LOOP2 ;DECREMENT X AND BRANCH TO LOOP1 IF RESULT
    STAA MIN
    CLRA
    CLRB
    LDX #16 ;INDEX X = 17
    LDY ARRAY ;INDEX Y = VALUE FROM MEMORY LOCATION VAR2
    LDA 0,ARRAY
LOOP3:
    MAXA 0,Y ;ADD 3 TO THE CONTENTS OF ACCUMULATOR A
    INCY
    DBNE X,LOOP3 ;DECREMENT X AND BRANCH TO LOOP1 IF RESULT
    STAA MAX
Done:
    RTS ;END OF "MAIN" FUNCTION